<?php
    $blogData = $block->getBlogData();
?>
<div class="simplenews">
   <?php
      if (count($blogData) > 0) :
   ?>
      <div class="toolbar top">
         <?php echo $block->getPagerHtml(); ?>
      </div>

      <ul>
         <?php foreach ($blogData as $blog) : ?>
            <li>
               <div class="simplenews-list">
                  <div class="simplenews-list-content">
                        <lable><p style="background-color: antiquewhite;">Title :</p></lable>
                        <?php echo $blog['title'] ?>
                  </div>
                  <div class="simplenews-list-content">
                    <lable><p style="background-color: antiquewhite;">Description :</p></lable>
                     <?php echo $blog['description'] ?>
                  </div>
                  <div class="simplenews-list-content">
                  <lable><p style="background-color: antiquewhite;">Content :</p></lable>
                    <?php 
                        echo $blog['content'];
                    ?>
                  </div>
                  <div class="simplenews-list-content">
                  <lable><p style="background-color: antiquewhite;">Firstname :</p></lable>
                    <?php 
                        echo $blog['firstname'];
                    ?>
                  </div>
                  <div class="simplenews-list-content">
                  <lable><p style="background-color: antiquewhite;">Lastname :</p></lable>
                    <?php 
                        echo $blog['lastname'];
                    ?>
                  </div>
                  <div class="simplenews-list-content">
                  <lable><p style="background-color: antiquewhite;">Username :</p></lable>
                    <?php 
                        echo $blog['username'];
                    ?>
                  </div>
                  <a class="news-title" href="<?php echo $this->getUrl('magenest/blog/view',['id' => $blog['id']]) ?>">View</a>
               </div>
            </li>
         <?php endforeach; ?>
      </ul>
      <div style="clear: both"></div>
      <div class="toolbar-bottom">
         <div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
      </div>
   <?php else : ?>
      <p><?php echo __('Have no article!') ?></p>
   <?php endif; ?>
</div>
<style>
.simplenews > ul {
   list-style: none;
   padding: 0;
}
.simplenews > ul li {
   padding: 10px 5px;
   margin: 0;
   background-color: #fff;
   border-bottom: 1px #c4c1bc solid;
   display: inline-block;
   width: 100%;
}
.simplenews > ul li:last-child {
   border-bottom: none;
}
.simplenews-list {
   float: left;
   position: relative;
   margin-left: 10px;
   width: 100%;
}
.simplenews-list a.news-title {
   font-weight: bold;
}
.simplenews-list a.news-title:hover {
   text-decoration: none;
}
.block-simplenews .block-title {
   margin: 0px 0px 20px;
}
.block-simplenews-heading {
   font-size: 18px;
   font-weight: 300;
}
</style>