<?php
    $dataMovie = $block->getData("data_view_movie");
    $chair = $block->getDataChair();
    $typeChair = $block->getChairData();
    $listChairData = $block->getListChair();

    $block->getPriceChair(1)[0]['price_movie'];
    // var_dump($block->getPriceChair(4)[0]['price_movie']);die();/// cuc suc vl :)))
    $type1 = [];$type2 = [];$type3 = [];
    foreach ($chair as $value) {
        if($value['chair_id']==1){array_push($type1, $value);}
        if($value['chair_id']==2){array_push($type2, $value);}
        if($value['chair_id']==3){array_push($type3, $value);}
    }
    // var_dump($dataMovie->getData());die();
?>
<div class="col-md-8 col-sm-8 col-xs-12">
    <section class="detail-feature">
        <article>
            <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-8 col-xs-offset-2 col-md-offset-0">
                    <div class="detail-feat-img">
                        <img src="" class="loading" data-was-processed="true">
                    </div>
                </div>
                <div class="details col-md-8 col-sm-8 col-xs-12">
                    <h2 class="detail-title upper-text"><?php echo $dataMovie->getData('name'); ?></h2>
                    <h2 class="detail-title vn upper-text"></h2>
                    <div class="detail-rating">
                    <span class="starrr stars-existing"></span>
                </div>
            </div>
        </article>
    </section>
</div>
<div class="detail-info">
    <div class="detail-info-row">
        <label>Thể loại:</label>
        <div class="detail-info-right">
            <a href="/dien-anh/the-loai/hai">Hài</a>
        </div>
    </div>
    <div class="detail-info-row">
        <label>Quốc gia:</label>
        <div class="detail-info-right">
            <a href="javascript:;">Mỹ</a>
        </div>
    </div>
    <div class="detail-info-row">
        <label>Nhà sản xuất:</label>
        <div class="detail-info-right">
            <a href="javascript:;">TSG Entertainment</a>
        </div>
    </div>
    <div class="detail-info-row">
        <label>Đạo diễn:</label>
        <div class="detail-info-right">
            <?php 
                $dataDirector = $block->getDataDirectorById($dataMovie->getData('director_id'));
                echo $dataDirector['name'];
            ?>
        </div>
    </div>
    <div class="detail-info-row">
        <label>Diễn viên:&nbsp;</label>
        <div class="detail-info-right">
            <?php 
                $arrayActorId = $block->getActorByMovie($dataMovie->getData('movie_id'));
                
                foreach($arrayActorId as $actorId){
                    $dataActor = $block->getDataActorById($actorId['actor_id']);
                    echo $dataActor['name'];
                }
                
            ?>
        </div>
    </div>
    <div class="detail-info-row">
        <label>Ngày:</label>
        <div class="detail-info-right">28/5/2021</div>
</div>
<div class="row detail-description">
    <div class="col-md-12 col sm-12 col-xs-12">
        <div class="content-text"><section id="info">
            <h3>Nội dung phim</h3>
            <div class="content-text-actors-info content-text">
                <?php echo  $dataMovie->getData('description'); ?>
            </div>
        </div>
    </div>
</div>
<button id="modal-btn-custom" type="submit" style="background-color: cadetblue;">Mua Vé Ngay</button>
<div id="modal-booking">
    <div class="room" style="text-align: center;">
        <?php foreach($typeChair as $type):?>
            <ul class="<?php echo $type['chair_id']?>">
            <?php foreach($listChairData as $item):?>
                <?php if($item['chair_id'] == $type['chair_id']):?>
                    <?php
                       $event = '';
                       if($item['chair_id'] == 1) $color = '#72bf72'; 
                       if($item['chair_id'] == 2) $color = '#ff0000';
                       if($item['chair_id'] == 3) $color = '#e66f97';
                    ?>
                    <?php 
                        if($item['status'] == 0): 
                        $color = '';
                    ?>
                    <li style="pointer-events:none; display: inline-block;border: 2px solid <?php echo $color?>" data-id="<?php echo $item['id']?>" data-price="<?php echo $block->getPriceChair($item['id'])[0]['price_movie']?>" ><?php echo $item['name']?></li>
                    <?php else: ?>
                    <li style="display: inline-block;border: 2px solid <?php echo $color?>" data-id="<?php echo $item['id']?>" data-price="<?php echo $block->getPriceChair($item['id'])[0]['price_movie']?>" ><?php echo $item['name']?></li>
                    <?php endif;?>
                <?php endif;?>
            <?php endforeach;?>
            </ul>
        <?php endforeach;?>
        <!-- <ul class="type-1">
            <li style="display: inline-block;border: 2px solid #72bf72;" data-id="a1">a1</li>
            <li style="display: inline-block;border: 2px solid #72bf72;" data-id="a2">a2</li>
            <li style="display: inline-block;border: 2px solid #72bf72;" data-id="a3">a3</li>
            <li style="display: inline-block;border: 2px solid #72bf72;" data-id="a4">a4</li>
            <li style="display: inline-block;border: 2px solid #72bf72;" data-id="a5">a5</li>
        </ul>
        <ul class="type-2">
            <li style="display: inline-block;border: 2px solid red;" data-id="b1">b1</li>
            <li style="display: inline-block;border: 2px solid red;" data-id="b2">b2</li>
            <li style="display: inline-block;border: 2px solid red;" data-id="b3">b3</li>
            <li style="display: inline-block;border: 2px solid red;" data-id="b4">b4</li>
            <li style="display: inline-block;border: 2px solid red;" data-id="b5">b5</li>
        </ul>
        <ul class="type-3">
            <li style="display: inline-block;border: 2px solid #e66f97;" data-id="c1">c1</li>
            <li style="display: inline-block;border: 2px solid #e66f97;" data-id="c2">c2</li>
            <li style="display: inline-block;border: 2px solid #e66f97;" data-id="c3">c3</li>
            <li style="display: inline-block;border: 2px solid #e66f97;" data-id="c4">c4</li>
            <li style="display: inline-block;border: 2px solid #e66f97;" data-id="c5">c5</li>
        </ul> -->
    </div>
    <lable>Thường</lable>
    <li style="display: list-item;
    border: 2px solid #72bf72;
    width: 30px;" data-id="a1"></li>
    <lable>Vip</lable>
    <li style="display: list-item;
    border: 2px solid red;
    width: 30px;" data-id="a1"></li>
    <lable>Đôi</lable>
    <li style="display: list-item;
    border: 2px solid #e66f97;
    width: 30px;" data-id="a1"></li>
    <div class="result" style="border-top: double; margin-top: 150px;">
        <table>
            <tr>
                <th>Rạp</th>
                <th>Galaxy Nguyen Hong Dao</th>
                <th>Tổng</th>
                <th class="price">đ</th>
            </tr>
            <tr>
                <th>Suất chiếu</th>
                <th>16:10,16/03/2021</th>
            </tr>
            <tr>
                <th>Phòng chiếu</th>
                <th>Cinema 5</th>
            </tr>
        </table>
        <button class="submit-value">Đặt Vé</button>
    </div>
</div>
<div class="messgean" id="messgean" style="display:none;">
    <div class="request--message-wrapper">
        <p class="title"><?php echo __('Đặt vé Thành Công') ?></p>
        <a class="done-request"href="<?php echo $this->getUrl() ?>"><?php echo __('DONE') ?></a>
    </div>
</div>
<script src=<?php echo $block->getViewFileUrl('Magenest_Movie::js/test.js')?>></script>
<script>
    require(
        [
            "jquery", 
            "Magento_Ui/js/modal/modal",
            "Magento_Ui/js/modal/alert"
        ],function($, modal, alert) {

            var options = {
                type: 'popup',
                responsive: true,
                title: 'Booking Ticket',
                buttons: [{ 
                    text: $.mage.__('Close'),
                    class: 'modal-close',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#modal-booking'));
            $("#modal-btn-custom").on('click',function(){
            $('#modal-booking').modal('openModal');
            });
        }
    );
    window.url = "<?php echo $block->getUrl('magenest/data/checkoutPost'); ?>";
</script>